steps:
- name: node
  entrypoint: npm
  args: ['install', 'express', '--save']

- name: gcr.io/cloud-builders/gcloud
    id  : DEPLOY
    args:
      - run
      - services
      - update
      
timeout: 1800s
