steps:
- name: node
  entrypoint: npm
  args: ['install', 'express', '--save']

- name: modify_package.json
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      echo $(cat package.json | sed 's/"test": "echo \\"Error: no test specified\\" && exit 1"/"start": "node index.js"/g') > package.json
  id: modify-package

- name: build_and_deploy
  entrypoint: npm
  args: ['run', 'build']
  timeout: 1800s

- name: deploy
  entrypoint: gcloud
  args: ['app', 'deploy']
