steps:
- name: node
  entrypoint: npm
  args: ['install', 'express', '--save']

- name: node
  entrypoint: npm
  args: ['run', 'index']
  
- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy']
      
timeout: 1800s
