steps:
- name: node
  entrypoint: npm
  args: ['install', 'express', '--save']

- name: build_and_deploy
  entrypoint: npm
  args: ['run', 'build']
  timeout: 1800s

- name: deploy
  entrypoint: gcloud
  args: ['app', 'deploy']
