steps:
# Docker Build Image
  - name: gcr.io/cloud-builders/docker
    id  : BUILD
    args: ['build', '-t', '$_SERVICE_IMAGE', '.', '-f', 'dockerfile']
    
# Docker Push Image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id  : PUSH
    args: ['push', '$_SERVICE_IMAGE']    

# Docker Deploy image to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    id  : DEPLOY
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --project=$_SERVICE_PROJECT
      - --region=$_SERVICE_REGION
      - --image=$_SERVICE_IMAGE

options:
    logging: CLOUD_LOGGING_ONLY

substitutions:
    _SERVICE_IMAGE    : europe-central2-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGENAME}:${SHORT_SHA}
    _SERVICE_REGION   : europe-central2
    _SERVICE_PROJECT  : prod-378614
    _SERVICE_NAME     : my-prod
    _DOCKER_REGISTRY  : cloud-run-source-deploy
    _DOCKER_IMAGENAME : gcp-js-app
